name: flutter_funky
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.0.0
  sqflite: ^2.0.0+4
  intl: ^0.17.0
  http: ^0.13.3
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_funcy_btn.png
    - assets/logo_funcy_splash.png
    - assets/logo_funcy_scale.png
    - assets/user_img.jpg
